# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-04 22:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0002_person_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
